# Generated by Django 5.1 on 2024-10-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations_balances', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosingBalance',
        ),
    ]
